create table if not exists public.sicas_ccj_report_runs (
  id uuid primary key default gen_random_uuid(),
  cache_key text not null,
  report_type text not null check (report_type in ('pendiente')),
  filters jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued', 'running', 'completed', 'failed')),
  next_page integer not null default 1 check (next_page > 0),
  source_rows_processed integer not null default 0 check (source_rows_processed >= 0),
  result_rows integer not null default 0 check (result_rows >= 0),
  requested_by uuid references auth.users(id) on delete set null,
  error text,
  started_at timestamptz,
  completed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists sicas_ccj_report_runs_one_active
  on public.sicas_ccj_report_runs (cache_key)
  where status in ('queued', 'running');

create index if not exists sicas_ccj_report_runs_lookup
  on public.sicas_ccj_report_runs (cache_key, created_at desc);

create table if not exists public.sicas_ccj_report_rows (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.sicas_ccj_report_runs(id) on delete cascade,
  source_page integer not null check (source_page > 0),
  source_index integer not null check (source_index >= 0),
  row_data jsonb not null,
  created_at timestamptz not null default now(),
  unique (run_id, source_page, source_index)
);

create index if not exists sicas_ccj_report_rows_run_order
  on public.sicas_ccj_report_rows (run_id, source_page, source_index);

alter table public.sicas_ccj_report_runs enable row level security;
alter table public.sicas_ccj_report_rows enable row level security;

revoke all on table public.sicas_ccj_report_runs from anon, authenticated;
revoke all on table public.sicas_ccj_report_rows from anon, authenticated;
grant select, insert, update, delete on table public.sicas_ccj_report_runs to service_role;
grant select, insert, update, delete on table public.sicas_ccj_report_rows to service_role;
grant usage, select on sequence public.sicas_ccj_report_rows_id_seq to service_role;

comment on table public.sicas_ccj_report_runs is
  'Estado de precargas asíncronas del reporte de cobranza pendiente SICAS CCJ.';
comment on table public.sicas_ccj_report_rows is
  'Filas normalizadas de SICAS asociadas a una precarga de cobranza pendiente.';
