
/*
  # Shared Quote Form Links System

  Creates the infrastructure for agents to share public quote form links
  with external clients who can fill them without logging in.

  ## New Tables

  ### shared_quote_form_links
  Stores each unique shareable link generated by an agent for a specific form type.
  - agent_id: the responsible agent who owns the link
  - slug: the unique public URL path (e.g. "rjimenez-auto-94irimc")
  - public_url: full URL at agentedeseguros.website
  - brand_config_json: snapshot of agent branding at time of creation
  - status: active | inactive | expired | deprecated

  ### shared_quote_form_submissions
  Stores each public submission received through a shared link.
  - Links to shared_quote_form_links, quote_forms, and tickets
  - Captures client contact data and form payload
  - Tracks IP hash and status of conversion

  ## Security
  - RLS enabled on both tables
  - Agents can only manage their own links
  - Gerentes can view their office's links
  - Admins have full access
  - Public submissions are inserted via service role (edge function)
*/

-- ─────────────────────────────────────────
-- Table: shared_quote_form_links
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shared_quote_form_links (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at              timestamptz DEFAULT now(),
  updated_at              timestamptz DEFAULT now(),
  created_by              uuid REFERENCES usuarios(id) ON DELETE SET NULL,
  agent_id                uuid REFERENCES usuarios(id) ON DELETE CASCADE NOT NULL,
  agent_slug              text NOT NULL,
  office_id               uuid REFERENCES oficinas(id) ON DELETE SET NULL,
  quote_form_template_id  uuid REFERENCES quote_form_templates(id) ON DELETE SET NULL,
  intelligent_agent_id    uuid,
  form_type               text NOT NULL,
  form_slug               text NOT NULL,
  form_title              text NOT NULL,
  unique_code             text NOT NULL,
  slug                    text NOT NULL UNIQUE,
  public_url              text NOT NULL,
  status                  text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'expired', 'deprecated')),
  brand_config_json       jsonb DEFAULT '{}',
  submissions_count       integer NOT NULL DEFAULT 0,
  last_submission_at      timestamptz,
  expires_at              timestamptz,
  metadata_json           jsonb DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_shared_links_agent_id    ON shared_quote_form_links(agent_id);
CREATE INDEX IF NOT EXISTS idx_shared_links_slug        ON shared_quote_form_links(slug);
CREATE INDEX IF NOT EXISTS idx_shared_links_form_type   ON shared_quote_form_links(form_type);
CREATE INDEX IF NOT EXISTS idx_shared_links_status      ON shared_quote_form_links(status);
CREATE INDEX IF NOT EXISTS idx_shared_links_office_id   ON shared_quote_form_links(office_id);

-- updated_at trigger
CREATE OR REPLACE FUNCTION set_shared_links_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_shared_links_updated_at ON shared_quote_form_links;
CREATE TRIGGER trg_shared_links_updated_at
  BEFORE UPDATE ON shared_quote_form_links
  FOR EACH ROW EXECUTE FUNCTION set_shared_links_updated_at();

-- ─────────────────────────────────────────
-- Table: shared_quote_form_submissions
-- ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shared_quote_form_submissions (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at              timestamptz DEFAULT now(),
  shared_link_id          uuid REFERENCES shared_quote_form_links(id) ON DELETE SET NULL,
  quote_form_id           uuid REFERENCES quote_forms(id) ON DELETE SET NULL,
  commercial_process_id   uuid,
  agent_id                uuid REFERENCES usuarios(id) ON DELETE SET NULL,
  agent_slug              text,
  office_id               uuid REFERENCES oficinas(id) ON DELETE SET NULL,
  form_type               text NOT NULL,
  form_slug               text,
  client_name             text,
  client_phone            text,
  client_whatsapp         text,
  client_email            text,
  data_json               jsonb DEFAULT '{}',
  attachments_json        jsonb DEFAULT '[]',
  ip_address_hash         text,
  user_agent              text,
  status                  text NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'converted_to_process', 'failed', 'spam_blocked'))
);

CREATE INDEX IF NOT EXISTS idx_submissions_shared_link_id ON shared_quote_form_submissions(shared_link_id);
CREATE INDEX IF NOT EXISTS idx_submissions_agent_id       ON shared_quote_form_submissions(agent_id);
CREATE INDEX IF NOT EXISTS idx_submissions_quote_form_id  ON shared_quote_form_submissions(quote_form_id);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at     ON shared_quote_form_submissions(created_at);

-- ─────────────────────────────────────────
-- Add source/channel columns to quote_forms
-- ─────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quote_forms' AND column_name='source') THEN
    ALTER TABLE quote_forms ADD COLUMN source text DEFAULT NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quote_forms' AND column_name='channel') THEN
    ALTER TABLE quote_forms ADD COLUMN channel text DEFAULT NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quote_forms' AND column_name='shared_link_id') THEN
    ALTER TABLE quote_forms ADD COLUMN shared_link_id uuid REFERENCES shared_quote_form_links(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quote_forms' AND column_name='public_submission_id') THEN
    ALTER TABLE quote_forms ADD COLUMN public_submission_id uuid REFERENCES shared_quote_form_submissions(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='quote_forms' AND column_name='manager_id') THEN
    ALTER TABLE quote_forms ADD COLUMN manager_id uuid REFERENCES usuarios(id) ON DELETE SET NULL;
  END IF;
END $$;

-- ─────────────────────────────────────────
-- RLS
-- ─────────────────────────────────────────
ALTER TABLE shared_quote_form_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared_quote_form_submissions ENABLE ROW LEVEL SECURITY;

-- shared_quote_form_links policies

CREATE POLICY "Agents can view own links"
  ON shared_quote_form_links FOR SELECT
  TO authenticated
  USING (agent_id = auth.uid());

CREATE POLICY "Gerentes can view office links"
  ON shared_quote_form_links FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM usuarios u
      WHERE u.id = auth.uid()
        AND u.rol IN ('Gerente', 'Administrador')
        AND (u.rol = 'Administrador' OR u.oficina_id = office_id)
    )
  );

CREATE POLICY "Agents can insert own links"
  ON shared_quote_form_links FOR INSERT
  TO authenticated
  WITH CHECK (agent_id = auth.uid() OR created_by = auth.uid());

CREATE POLICY "Agents can update own links"
  ON shared_quote_form_links FOR UPDATE
  TO authenticated
  USING (agent_id = auth.uid())
  WITH CHECK (agent_id = auth.uid());

CREATE POLICY "Admins can update any link"
  ON shared_quote_form_links FOR UPDATE
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND rol = 'Administrador')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND rol = 'Administrador')
  );

-- shared_quote_form_submissions policies

CREATE POLICY "Agents can view own submissions"
  ON shared_quote_form_submissions FOR SELECT
  TO authenticated
  USING (agent_id = auth.uid());

CREATE POLICY "Gerentes can view office submissions"
  ON shared_quote_form_submissions FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM usuarios u
      WHERE u.id = auth.uid()
        AND u.rol IN ('Gerente', 'Administrador')
        AND (u.rol = 'Administrador' OR u.oficina_id = office_id)
    )
  );

-- Service role inserts submissions (edge function runs as service role)
CREATE POLICY "Service role can insert submissions"
  ON shared_quote_form_submissions FOR INSERT
  TO service_role
  WITH CHECK (true);

-- Allow service role to update submissions
CREATE POLICY "Service role can update submissions"
  ON shared_quote_form_submissions FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Service role can also update shared links (increment counter)
CREATE POLICY "Service role can update links"
  ON shared_quote_form_links FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Public read of active links by slug (for public form page)
CREATE POLICY "Public can read active links by slug"
  ON shared_quote_form_links FOR SELECT
  TO anon
  USING (status = 'active');

-- ─────────────────────────────────────────
-- Helper function: resolve agent branding snapshot
-- ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION get_agent_brand_config(p_agent_id uuid)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user RECORD;
  v_office RECORD;
  v_brand jsonb;
BEGIN
  SELECT nombre, apellido_paterno, apellido_materno, oficina_id, nombre_publico,
         correo_laboral, foto_perfil
    INTO v_user
    FROM usuarios
   WHERE id = p_agent_id;

  IF v_user.oficina_id IS NOT NULL THEN
    SELECT nombre, logo_url, color_acento INTO v_office
      FROM oficinas WHERE id = v_user.oficina_id;
  END IF;

  v_brand := jsonb_build_object(
    'agent_name',       COALESCE(v_user.nombre_publico, v_user.nombre || ' ' || COALESCE(v_user.apellido_paterno, '')),
    'office_name',      COALESCE(v_office.nombre, ''),
    'primary_color',    COALESCE(v_office.color_acento, '#2563eb'),
    'secondary_color',  '#1e40af',
    'logo_url',         COALESCE(v_user.foto_perfil, v_office.logo_url, '/logojiro.png'),
    'footer_text',      'Formulario enviado a través de MOVI Digital.'
  );

  RETURN v_brand;
END;
$$;

GRANT EXECUTE ON FUNCTION get_agent_brand_config(uuid) TO authenticated, anon, service_role;
