/*
  # Create SICAS Cartera Module Tables

  1. New Tables
    - `sicas_customer_profiles`
      - Normalized client records derived from sicas_documents
      - Aggregates policy info per client
      - Links to MOVI user (agent) who owns the client
    - `sicas_agent_alerts`
      - Alert system for agents about renewals, opportunities, performance
      - Priority-based with status tracking
    - `sicas_cross_sell_opportunities`
      - Detected cross-sell opportunities based on portfolio analysis
      - Rule-based detection with suggested actions
    - `sicas_renewal_followups`
      - Renewal follow-up tracking with status workflow
      - Links to customer profile and policy

  2. Security
    - RLS enabled on all tables
    - Agents only see their own data
    - Gerentes see office data
    - Admins see all

  3. Important Notes
    - sicas_customer_profiles is populated from sicas_documents client data
    - Alerts are generated by background processes or on-demand
    - Opportunities use simple rule-based detection from portfolio composition
*/

-- ============================================================
-- Table: sicas_customer_profiles
-- Normalized client records from SICAS documents
-- ============================================================
CREATE TABLE IF NOT EXISTS sicas_customer_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL REFERENCES usuarios(id),
  sicas_vendor_id text,
  oficina_id uuid REFERENCES oficinas(id),
  client_name text NOT NULL,
  normalized_name text NOT NULL,
  rfc text,
  email text,
  phone text,
  address text,
  sicas_client_id text,
  total_policies_active integer DEFAULT 0,
  total_policies_expired integer DEFAULT 0,
  total_premium_active numeric(15,2) DEFAULT 0,
  total_premium_expired numeric(15,2) DEFAULT 0,
  ramos_activos text[] DEFAULT '{}',
  aseguradoras_activas text[] DEFAULT '{}',
  next_renewal_date date,
  last_emission_date date,
  last_activity_at timestamptz,
  portfolio_status text DEFAULT 'active' CHECK (portfolio_status IN ('active', 'renewing', 'expired', 'lost', 'no_followup')),
  is_high_value boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sicas_customer_profiles_usuario ON sicas_customer_profiles(usuario_id);
CREATE INDEX IF NOT EXISTS idx_sicas_customer_profiles_oficina ON sicas_customer_profiles(oficina_id);
CREATE INDEX IF NOT EXISTS idx_sicas_customer_profiles_normalized_name ON sicas_customer_profiles(normalized_name);
CREATE INDEX IF NOT EXISTS idx_sicas_customer_profiles_rfc ON sicas_customer_profiles(rfc);
CREATE INDEX IF NOT EXISTS idx_sicas_customer_profiles_next_renewal ON sicas_customer_profiles(next_renewal_date);
CREATE INDEX IF NOT EXISTS idx_sicas_customer_profiles_status ON sicas_customer_profiles(portfolio_status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sicas_customer_profiles_unique_client ON sicas_customer_profiles(usuario_id, normalized_name) WHERE rfc IS NULL;

ALTER TABLE sicas_customer_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Agents see own customer profiles"
  ON sicas_customer_profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = usuario_id);

CREATE POLICY "Agents insert own customer profiles"
  ON sicas_customer_profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Agents update own customer profiles"
  ON sicas_customer_profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = usuario_id)
  WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Service role full access customer profiles"
  ON sicas_customer_profiles FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- Table: sicas_agent_alerts
-- Alert system for agents
-- ============================================================
CREATE TABLE IF NOT EXISTS sicas_agent_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL REFERENCES usuarios(id),
  sicas_vendor_id text,
  oficina_id uuid REFERENCES oficinas(id),
  customer_profile_id uuid REFERENCES sicas_customer_profiles(id) ON DELETE SET NULL,
  document_id text,
  policy_number text,
  alert_type text NOT NULL CHECK (alert_type IN (
    'renewal_upcoming', 'policy_expired', 'new_emission', 'document_available',
    'no_followup', 'cross_sell', 'production_low', 'high_value_renewal',
    'recoverable_policy'
  )),
  priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
  title text NOT NULL,
  description text,
  client_name text,
  recommended_action text,
  related_data jsonb DEFAULT '{}',
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'seen', 'in_followup', 'resolved', 'dismissed')),
  due_date date,
  resolved_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sicas_agent_alerts_usuario ON sicas_agent_alerts(usuario_id);
CREATE INDEX IF NOT EXISTS idx_sicas_agent_alerts_status ON sicas_agent_alerts(status);
CREATE INDEX IF NOT EXISTS idx_sicas_agent_alerts_type ON sicas_agent_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_sicas_agent_alerts_priority ON sicas_agent_alerts(priority);
CREATE INDEX IF NOT EXISTS idx_sicas_agent_alerts_due_date ON sicas_agent_alerts(due_date);
CREATE INDEX IF NOT EXISTS idx_sicas_agent_alerts_created ON sicas_agent_alerts(created_at DESC);

ALTER TABLE sicas_agent_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Agents see own alerts"
  ON sicas_agent_alerts FOR SELECT
  TO authenticated
  USING (auth.uid() = usuario_id);

CREATE POLICY "Agents update own alerts"
  ON sicas_agent_alerts FOR UPDATE
  TO authenticated
  USING (auth.uid() = usuario_id)
  WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Service role full access alerts"
  ON sicas_agent_alerts FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- Table: sicas_cross_sell_opportunities
-- Detected cross-sell opportunities
-- ============================================================
CREATE TABLE IF NOT EXISTS sicas_cross_sell_opportunities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL REFERENCES usuarios(id),
  sicas_vendor_id text,
  oficina_id uuid REFERENCES oficinas(id),
  customer_profile_id uuid REFERENCES sicas_customer_profiles(id) ON DELETE CASCADE,
  client_name text NOT NULL,
  opportunity_type text NOT NULL CHECK (opportunity_type IN (
    'auto_sin_gmm', 'auto_sin_hogar', 'vida_sin_gmm',
    'single_policy', 'high_value_client', 'recoverable_policy',
    'diversification', 'upgrade'
  )),
  current_products text[] DEFAULT '{}',
  suggested_product text,
  priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
  description text,
  recommended_message text,
  premium_current numeric(15,2) DEFAULT 0,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'quoted', 'converted', 'dismissed')),
  contacted_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sicas_opportunities_usuario ON sicas_cross_sell_opportunities(usuario_id);
CREATE INDEX IF NOT EXISTS idx_sicas_opportunities_status ON sicas_cross_sell_opportunities(status);
CREATE INDEX IF NOT EXISTS idx_sicas_opportunities_type ON sicas_cross_sell_opportunities(opportunity_type);
CREATE INDEX IF NOT EXISTS idx_sicas_opportunities_customer ON sicas_cross_sell_opportunities(customer_profile_id);

ALTER TABLE sicas_cross_sell_opportunities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Agents see own opportunities"
  ON sicas_cross_sell_opportunities FOR SELECT
  TO authenticated
  USING (auth.uid() = usuario_id);

CREATE POLICY "Agents update own opportunities"
  ON sicas_cross_sell_opportunities FOR UPDATE
  TO authenticated
  USING (auth.uid() = usuario_id)
  WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Service role full access opportunities"
  ON sicas_cross_sell_opportunities FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- Table: sicas_renewal_followups
-- Renewal follow-up tracking
-- ============================================================
CREATE TABLE IF NOT EXISTS sicas_renewal_followups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid NOT NULL REFERENCES usuarios(id),
  customer_profile_id uuid REFERENCES sicas_customer_profiles(id) ON DELETE SET NULL,
  document_id text,
  policy_number text,
  client_name text NOT NULL,
  insurer text,
  ramo text,
  premium numeric(15,2) DEFAULT 0,
  expiry_date date NOT NULL,
  days_remaining integer,
  renewal_status text NOT NULL DEFAULT 'pending' CHECK (renewal_status IN (
    'pending', 'contacted', 'quoted', 'renewed', 'lost', 'deferred'
  )),
  last_contacted_at timestamptz,
  next_followup_at timestamptz,
  contact_method text,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sicas_renewal_followups_usuario ON sicas_renewal_followups(usuario_id);
CREATE INDEX IF NOT EXISTS idx_sicas_renewal_followups_status ON sicas_renewal_followups(renewal_status);
CREATE INDEX IF NOT EXISTS idx_sicas_renewal_followups_expiry ON sicas_renewal_followups(expiry_date);
CREATE INDEX IF NOT EXISTS idx_sicas_renewal_followups_customer ON sicas_renewal_followups(customer_profile_id);

ALTER TABLE sicas_renewal_followups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Agents see own renewal followups"
  ON sicas_renewal_followups FOR SELECT
  TO authenticated
  USING (auth.uid() = usuario_id);

CREATE POLICY "Agents insert own renewal followups"
  ON sicas_renewal_followups FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Agents update own renewal followups"
  ON sicas_renewal_followups FOR UPDATE
  TO authenticated
  USING (auth.uid() = usuario_id)
  WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Service role full access renewal followups"
  ON sicas_renewal_followups FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- Function: Refresh customer profiles from sicas_documents
-- ============================================================
CREATE OR REPLACE FUNCTION refresh_sicas_customer_profiles(p_usuario_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_vendor_id text;
  v_oficina_id uuid;
  v_count integer := 0;
BEGIN
  -- Get user's vendor mapping
  SELECT smvu.id_sicas_vendedor INTO v_vendor_id
  FROM sicas_mapeo_vendedor_usuario smvu
  WHERE smvu.movi_user_id = p_usuario_id
  LIMIT 1;

  IF v_vendor_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'No vendor mapping found');
  END IF;

  -- Get office
  SELECT oficina_id INTO v_oficina_id FROM usuarios WHERE id = p_usuario_id;

  -- Upsert customer profiles from documents
  INSERT INTO sicas_customer_profiles (
    usuario_id, sicas_vendor_id, oficina_id, client_name, normalized_name, 
    total_policies_active, total_premium_active, ramos_activos, aseguradoras_activas,
    next_renewal_date, last_emission_date, last_activity_at, portfolio_status
  )
  SELECT
    p_usuario_id,
    v_vendor_id,
    v_oficina_id,
    d.cliente,
    upper(trim(regexp_replace(d.cliente, '\s+', ' ', 'g'))),
    count(*) FILTER (WHERE d.is_vigente = true),
    coalesce(sum(d.prima_neta) FILTER (WHERE d.is_vigente = true), 0),
    array_agg(DISTINCT d.ramo) FILTER (WHERE d.ramo IS NOT NULL AND d.is_vigente = true),
    array_agg(DISTINCT d.compania) FILTER (WHERE d.compania IS NOT NULL AND d.is_vigente = true),
    min(d.vigencia_hasta) FILTER (WHERE d.is_vigente = true AND d.vigencia_hasta > now()),
    max(d.fecha_captura),
    max(d.synced_at),
    CASE
      WHEN count(*) FILTER (WHERE d.is_vigente = true AND d.vigencia_hasta BETWEEN now() AND now() + interval '30 days') > 0 THEN 'renewing'
      WHEN count(*) FILTER (WHERE d.is_vigente = true) > 0 THEN 'active'
      WHEN count(*) FILTER (WHERE d.is_vigente = false AND d.vigencia_hasta > now() - interval '90 days') > 0 THEN 'expired'
      ELSE 'lost'
    END
  FROM sicas_documents d
  WHERE d.usuario_id = p_usuario_id
    AND d.cliente IS NOT NULL
    AND trim(d.cliente) != ''
  GROUP BY d.cliente
  ON CONFLICT (usuario_id, normalized_name) WHERE rfc IS NULL
  DO UPDATE SET
    total_policies_active = EXCLUDED.total_policies_active,
    total_premium_active = EXCLUDED.total_premium_active,
    ramos_activos = EXCLUDED.ramos_activos,
    aseguradoras_activas = EXCLUDED.aseguradoras_activas,
    next_renewal_date = EXCLUDED.next_renewal_date,
    last_emission_date = EXCLUDED.last_emission_date,
    last_activity_at = EXCLUDED.last_activity_at,
    portfolio_status = EXCLUDED.portfolio_status,
    updated_at = now();

  GET DIAGNOSTICS v_count = ROW_COUNT;

  -- Mark high-value clients (top 20% by premium)
  WITH ranked AS (
    SELECT id, total_premium_active,
      ntile(5) OVER (ORDER BY total_premium_active DESC) as quintile
    FROM sicas_customer_profiles
    WHERE usuario_id = p_usuario_id AND total_policies_active > 0
  )
  UPDATE sicas_customer_profiles cp
  SET is_high_value = (r.quintile = 1)
  FROM ranked r
  WHERE cp.id = r.id;

  RETURN jsonb_build_object('success', true, 'profiles_updated', v_count);
END;
$$;

-- ============================================================
-- Function: Generate alerts for an agent
-- ============================================================
CREATE OR REPLACE FUNCTION generate_sicas_agent_alerts(p_usuario_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_alerts_created integer := 0;
  v_vendor_id text;
BEGIN
  SELECT smvu.id_sicas_vendedor INTO v_vendor_id
  FROM sicas_mapeo_vendedor_usuario smvu
  WHERE smvu.movi_user_id = p_usuario_id
  LIMIT 1;

  IF v_vendor_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'No vendor mapping');
  END IF;

  -- Clear old unresolved alerts older than 90 days
  DELETE FROM sicas_agent_alerts
  WHERE usuario_id = p_usuario_id
    AND status = 'new'
    AND created_at < now() - interval '90 days';

  -- Alert: Renewals within 15 days (HIGH priority)
  INSERT INTO sicas_agent_alerts (usuario_id, sicas_vendor_id, alert_type, priority, title, description, client_name, document_id, policy_number, due_date, recommended_action, related_data)
  SELECT
    p_usuario_id, v_vendor_id, 'renewal_upcoming', 'high',
    'Renovacion urgente: ' || d.cliente,
    'La poliza ' || coalesce(d.poliza, d.id_docto) || ' de ' || d.compania || ' vence en ' || 
      extract(day from d.vigencia_hasta - now())::integer || ' dias.',
    d.cliente, d.id_docto, d.poliza, d.vigencia_hasta::date,
    'Contactar al cliente para asegurar la renovacion.',
    jsonb_build_object('ramo', d.ramo, 'aseguradora', d.compania, 'prima_neta', d.prima_neta)
  FROM sicas_documents d
  WHERE d.usuario_id = p_usuario_id
    AND d.is_vigente = true
    AND d.vigencia_hasta BETWEEN now() AND now() + interval '15 days'
    AND NOT EXISTS (
      SELECT 1 FROM sicas_agent_alerts a
      WHERE a.usuario_id = p_usuario_id
        AND a.document_id = d.id_docto
        AND a.alert_type = 'renewal_upcoming'
        AND a.created_at > now() - interval '30 days'
    );
  GET DIAGNOSTICS v_alerts_created = ROW_COUNT;

  -- Alert: Renewals 15-30 days (MEDIUM priority)
  INSERT INTO sicas_agent_alerts (usuario_id, sicas_vendor_id, alert_type, priority, title, description, client_name, document_id, policy_number, due_date, recommended_action, related_data)
  SELECT
    p_usuario_id, v_vendor_id, 'renewal_upcoming', 'medium',
    'Renovacion proxima: ' || d.cliente,
    'La poliza ' || coalesce(d.poliza, d.id_docto) || ' vence el ' || to_char(d.vigencia_hasta, 'DD/MM/YYYY') || '.',
    d.cliente, d.id_docto, d.poliza, d.vigencia_hasta::date,
    'Programar contacto con el cliente.',
    jsonb_build_object('ramo', d.ramo, 'aseguradora', d.compania, 'prima_neta', d.prima_neta)
  FROM sicas_documents d
  WHERE d.usuario_id = p_usuario_id
    AND d.is_vigente = true
    AND d.vigencia_hasta BETWEEN now() + interval '15 days' AND now() + interval '30 days'
    AND NOT EXISTS (
      SELECT 1 FROM sicas_agent_alerts a
      WHERE a.usuario_id = p_usuario_id
        AND a.document_id = d.id_docto
        AND a.alert_type = 'renewal_upcoming'
        AND a.created_at > now() - interval '30 days'
    );

  -- Alert: Expired policies recoverable (< 90 days)
  INSERT INTO sicas_agent_alerts (usuario_id, sicas_vendor_id, alert_type, priority, title, description, client_name, document_id, policy_number, due_date, recommended_action, related_data)
  SELECT
    p_usuario_id, v_vendor_id, 'recoverable_policy', 'high',
    'Poliza vencida recuperable: ' || d.cliente,
    'La poliza ' || coalesce(d.poliza, d.id_docto) || ' vencio hace ' || 
      extract(day from now() - d.vigencia_hasta)::integer || ' dias. Aun se puede recuperar.',
    d.cliente, d.id_docto, d.poliza, d.vigencia_hasta::date,
    'Contactar al cliente para reactivar la poliza.',
    jsonb_build_object('ramo', d.ramo, 'aseguradora', d.compania, 'prima_neta', d.prima_neta)
  FROM sicas_documents d
  WHERE d.usuario_id = p_usuario_id
    AND d.is_vigente = false
    AND d.vigencia_hasta BETWEEN now() - interval '90 days' AND now()
    AND NOT EXISTS (
      SELECT 1 FROM sicas_agent_alerts a
      WHERE a.usuario_id = p_usuario_id
        AND a.document_id = d.id_docto
        AND a.alert_type = 'recoverable_policy'
        AND a.created_at > now() - interval '30 days'
    );

  -- Alert: High-value renewals (top premium policies renewing soon)
  INSERT INTO sicas_agent_alerts (usuario_id, sicas_vendor_id, alert_type, priority, title, description, client_name, document_id, policy_number, due_date, recommended_action, related_data)
  SELECT
    p_usuario_id, v_vendor_id, 'high_value_renewal', 'high',
    'Renovacion de alta prima: ' || d.cliente,
    'Poliza con prima de $' || to_char(d.prima_neta, 'FM999,999,999') || ' vence el ' || to_char(d.vigencia_hasta, 'DD/MM/YYYY') || '.',
    d.cliente, d.id_docto, d.poliza, d.vigencia_hasta::date,
    'Dar seguimiento prioritario a esta renovacion de alta prima.',
    jsonb_build_object('ramo', d.ramo, 'aseguradora', d.compania, 'prima_neta', d.prima_neta)
  FROM sicas_documents d
  WHERE d.usuario_id = p_usuario_id
    AND d.is_vigente = true
    AND d.vigencia_hasta BETWEEN now() AND now() + interval '60 days'
    AND d.prima_neta > (
      SELECT percentile_cont(0.8) WITHIN GROUP (ORDER BY prima_neta)
      FROM sicas_documents WHERE usuario_id = p_usuario_id AND is_vigente = true AND prima_neta > 0
    )
    AND NOT EXISTS (
      SELECT 1 FROM sicas_agent_alerts a
      WHERE a.usuario_id = p_usuario_id
        AND a.document_id = d.id_docto
        AND a.alert_type = 'high_value_renewal'
        AND a.created_at > now() - interval '30 days'
    );

  RETURN jsonb_build_object('success', true, 'alerts_created', v_alerts_created);
END;
$$;

-- ============================================================
-- Function: Detect cross-sell opportunities
-- ============================================================
CREATE OR REPLACE FUNCTION detect_sicas_cross_sell(p_usuario_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_created integer := 0;
  v_vendor_id text;
  v_oficina_id uuid;
BEGIN
  SELECT smvu.id_sicas_vendedor INTO v_vendor_id
  FROM sicas_mapeo_vendedor_usuario smvu
  WHERE smvu.movi_user_id = p_usuario_id
  LIMIT 1;

  SELECT oficina_id INTO v_oficina_id FROM usuarios WHERE id = p_usuario_id;

  IF v_vendor_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'No vendor mapping');
  END IF;

  -- Clear old dismissed/converted opportunities older than 90 days
  DELETE FROM sicas_cross_sell_opportunities
  WHERE usuario_id = p_usuario_id
    AND status IN ('dismissed', 'converted')
    AND updated_at < now() - interval '90 days';

  -- Rule: Auto sin GMM
  INSERT INTO sicas_cross_sell_opportunities (
    usuario_id, sicas_vendor_id, oficina_id, customer_profile_id, client_name,
    opportunity_type, current_products, suggested_product, priority, description,
    recommended_message, premium_current
  )
  SELECT
    p_usuario_id, v_vendor_id, v_oficina_id, cp.id, cp.client_name,
    'auto_sin_gmm', cp.ramos_activos, 'Gastos Medicos Mayores', 'medium',
    'Cliente con Auto activo sin GMM. Puede ser candidato para proteccion familiar.',
    'Hola ' || split_part(cp.client_name, ' ', 1) || ', te escribo porque vi que tienes tu seguro de Auto con nosotros. Me gustaria platicarte sobre opciones de Gastos Medicos Mayores para complementar tu proteccion.',
    cp.total_premium_active
  FROM sicas_customer_profiles cp
  WHERE cp.usuario_id = p_usuario_id
    AND cp.total_policies_active > 0
    AND 'AUTOS' = ANY(cp.ramos_activos) OR 'AUTOMOVILES' = ANY(cp.ramos_activos)
    AND NOT ('GMM' = ANY(cp.ramos_activos) OR 'GASTOS MEDICOS' = ANY(cp.ramos_activos) OR 'GASTOS MEDICOS MAYORES' = ANY(cp.ramos_activos))
    AND NOT EXISTS (
      SELECT 1 FROM sicas_cross_sell_opportunities o
      WHERE o.usuario_id = p_usuario_id AND o.customer_profile_id = cp.id AND o.opportunity_type = 'auto_sin_gmm'
    );
  GET DIAGNOSTICS v_created = ROW_COUNT;

  -- Rule: Single policy client
  INSERT INTO sicas_cross_sell_opportunities (
    usuario_id, sicas_vendor_id, oficina_id, customer_profile_id, client_name,
    opportunity_type, current_products, suggested_product, priority, description,
    recommended_message, premium_current
  )
  SELECT
    p_usuario_id, v_vendor_id, v_oficina_id, cp.id, cp.client_name,
    'single_policy', cp.ramos_activos, 'Venta cruzada', 'low',
    'Cliente con una sola poliza. Puede ser candidato a venta cruzada.',
    'Hola ' || split_part(cp.client_name, ' ', 1) || ', me gustaria platicarte sobre opciones adicionales de proteccion que podrian complementar tu seguro actual.',
    cp.total_premium_active
  FROM sicas_customer_profiles cp
  WHERE cp.usuario_id = p_usuario_id
    AND cp.total_policies_active = 1
    AND NOT EXISTS (
      SELECT 1 FROM sicas_cross_sell_opportunities o
      WHERE o.usuario_id = p_usuario_id AND o.customer_profile_id = cp.id AND o.opportunity_type = 'single_policy'
    );

  -- Rule: High-value client
  INSERT INTO sicas_cross_sell_opportunities (
    usuario_id, sicas_vendor_id, oficina_id, customer_profile_id, client_name,
    opportunity_type, current_products, suggested_product, priority, description,
    recommended_message, premium_current
  )
  SELECT
    p_usuario_id, v_vendor_id, v_oficina_id, cp.id, cp.client_name,
    'high_value_client', cp.ramos_activos, 'Seguimiento prioritario', 'high',
    'Cliente de alta prima. Conviene darle seguimiento prioritario.',
    'Hola ' || split_part(cp.client_name, ' ', 1) || ', como tu asesor me gustaria revisar contigo tus coberturas actuales para asegurarme de que tengas la mejor proteccion posible.',
    cp.total_premium_active
  FROM sicas_customer_profiles cp
  WHERE cp.usuario_id = p_usuario_id
    AND cp.is_high_value = true
    AND cp.total_policies_active >= 2
    AND NOT EXISTS (
      SELECT 1 FROM sicas_cross_sell_opportunities o
      WHERE o.usuario_id = p_usuario_id AND o.customer_profile_id = cp.id AND o.opportunity_type = 'high_value_client'
    );

  -- Rule: Recoverable policy
  INSERT INTO sicas_cross_sell_opportunities (
    usuario_id, sicas_vendor_id, oficina_id, customer_profile_id, client_name,
    opportunity_type, current_products, suggested_product, priority, description,
    recommended_message, premium_current
  )
  SELECT
    p_usuario_id, v_vendor_id, v_oficina_id, cp.id, cp.client_name,
    'recoverable_policy', cp.ramos_activos, 'Reactivacion', 'high',
    'Cliente con poliza vencida recuperable. Conviene contactarlo para reactivacion.',
    'Hola ' || split_part(cp.client_name, ' ', 1) || ', te escribo porque note que tu poliza vencio recientemente. Me gustaria ayudarte a renovarla para que sigas protegido.',
    cp.total_premium_active
  FROM sicas_customer_profiles cp
  WHERE cp.usuario_id = p_usuario_id
    AND cp.portfolio_status = 'expired'
    AND cp.total_policies_expired > 0
    AND NOT EXISTS (
      SELECT 1 FROM sicas_cross_sell_opportunities o
      WHERE o.usuario_id = p_usuario_id AND o.customer_profile_id = cp.id AND o.opportunity_type = 'recoverable_policy'
    );

  RETURN jsonb_build_object('success', true, 'opportunities_created', v_created);
END;
$$;
