/*
  # Update seguwallet_insurers with 27 Mexican insurance companies

  1. Changes
    - Soft-deletes all existing seguwallet_insurers rows
    - Inserts 27 new insurance companies with complete data
    - Uses ON CONFLICT (name) to avoid duplicates on re-run
*/

-- Soft-delete all existing rows
UPDATE seguwallet_insurers
SET deleted_at = now()
WHERE deleted_at IS NULL;

-- Insert the 27 companies
INSERT INTO seguwallet_insurers (
  name, logo_url,
  customer_service_phone, claims_phone, claims_whatsapp,
  payment_url, ios_app_url, android_app_url, general_conditions_url,
  claims_instructions,
  show_in_directory, show_in_claims, is_active, display_order
) VALUES
('GNP Seguros', 'https://logo.clearbit.com/gnp.com.mx',
  '8008003456', '8008003456', '5519282800',
  'https://www.gnp.com.mx/pago-en-linea',
  'https://apps.apple.com/mx/app/gnp-seguros/id1465763424',
  'https://play.google.com/store/apps/details?id=mx.com.gnp.gnpapp',
  'https://www.gnp.com.mx/seguros/condiciones-generales',
  'Ten a la mano tu numero de poliza, nombre del asegurado y detalles del siniestro.',
  true, true, true, 1),
('AXA Seguros', 'https://logo.clearbit.com/axa.com.mx',
  '8005620000', '8005620000', NULL,
  'https://www.axa.com.mx/pago-en-linea',
  'https://apps.apple.com/mx/app/axa-mexico/id1097282050',
  'https://play.google.com/store/apps/details?id=mx.com.axa.axamx',
  'https://www.axa.com.mx/seguros/condiciones-generales',
  'Comunicate de inmediato para iniciar tu reporte. Ten disponible tu numero de poliza.',
  true, true, true, 2),
('Qualitas', 'https://logo.clearbit.com/qualitas.com.mx',
  '8008312444', '8008312444', NULL,
  'https://www.qualitas.com.mx/pagos',
  'https://apps.apple.com/mx/app/qualitas-movil/id1462766556',
  'https://play.google.com/store/apps/details?id=com.qualitas.qualitasmovil',
  'https://www.qualitas.com.mx/condiciones-generales',
  'Reporta tu siniestro de auto las 24 horas. Ten a la mano datos del vehiculo y numero de poliza.',
  true, true, true, 3),
('Chubb Seguros', 'https://logo.clearbit.com/chubb.com',
  '5552490000', '8008904800', NULL,
  'https://www.chubb.com/mx-es/pagos',
  NULL, NULL,
  'https://www.chubb.com/mx-es/condiciones-generales',
  'Para siniestros de hogar, vida o empresariales contacta la linea especializada.',
  true, true, true, 4),
('MAPFRE Mexico', 'https://logo.clearbit.com/mapfre.com.mx',
  '8009002000', '8009002000', NULL,
  'https://www.mapfre.com.mx/pagos',
  'https://apps.apple.com/mx/app/mapfre-mexico/id1478238946',
  'https://play.google.com/store/apps/details?id=com.mapfre.mexico',
  'https://www.mapfre.com.mx/condiciones-generales',
  'Reporta tu siniestro las 24 horas del dia. Ten disponible tu numero de poliza.',
  true, true, true, 5),
('HDI Seguros', 'https://logo.clearbit.com/hdi.com.mx',
  '5552003330', '8008904900', NULL,
  'https://www.hdi.com.mx/pagos',
  NULL, NULL,
  'https://www.hdi.com.mx/condiciones-generales',
  'Llama de inmediato para recibir asistencia. Tendras un ajustador en camino.',
  true, true, true, 6),
('Zurich Seguros', 'https://logo.clearbit.com/zurich.com.mx',
  '8009001000', '8009001000', NULL,
  'https://www.zurich.com.mx/pagos',
  NULL, NULL,
  'https://www.zurich.com.mx/condiciones-generales',
  'Servicio de siniestros disponible las 24 horas. Proporciona tu numero de poliza al llamar.',
  true, true, true, 7),
('MetLife Mexico', 'https://logo.clearbit.com/metlife.com.mx',
  '8008361111', '8008361111', NULL,
  'https://www.metlife.com.mx/pagos',
  'https://apps.apple.com/mx/app/mybenefits-metlife-mexico/id1455024074',
  'https://play.google.com/store/apps/details?id=com.metlife.mybenefitsapp',
  'https://www.metlife.com.mx/condiciones-generales',
  'Para siniestros de vida, gastos medicos o accidentes personales, contacta nuestra linea especializada.',
  true, true, true, 8),
('Allianz Mexico', 'https://logo.clearbit.com/allianz.com.mx',
  '5552270000', '8005222500', NULL,
  'https://www.allianz.com.mx/pagos',
  NULL, NULL,
  'https://www.allianz.com.mx/condiciones-generales',
  'Reporta de inmediato. Nuestro equipo de siniestros te orientara en cada paso.',
  true, true, true, 9),
('Seguros Atlas', 'https://logo.clearbit.com/atlas.com.mx',
  '3336691111', '3336691111', NULL,
  'https://www.atlas.com.mx/pagos',
  NULL, NULL,
  'https://www.atlas.com.mx/condiciones-generales',
  'Atencion de siniestros en el occidente del pais. Ten tu poliza a la mano.',
  true, true, true, 10),
('Seguros SURA', 'https://logo.clearbit.com/sura.com.mx',
  '8008081000', '8008081000', NULL,
  'https://www.sura.com.mx/pagos',
  NULL, NULL,
  'https://www.sura.com.mx/condiciones-generales',
  'Reporta tu siniestro las 24 horas. Nuestro equipo esta listo para asistirte.',
  true, true, true, 11),
('Bupa Mexico', 'https://logo.clearbit.com/bupamexico.com.mx',
  '8002002882', '8002002882', NULL,
  'https://www.bupamexico.com.mx/pagos',
  NULL, NULL,
  'https://www.bupamexico.com.mx/condiciones-generales',
  'Para reembolsos y autorizaciones de gastos medicos mayores, contacta nuestra linea.',
  true, true, true, 12),
('ANA Seguros', 'https://logo.clearbit.com/ana.com.mx',
  '8009002100', '8009002100', NULL,
  'https://www.ana.com.mx/pagos',
  NULL, NULL,
  'https://www.ana.com.mx/condiciones-generales',
  'Reporta tu siniestro de autos. Ten disponible tu numero de poliza y datos del evento.',
  true, true, true, 13),
('Inbursa Seguros', 'https://logo.clearbit.com/inbursa.com',
  '5552229000', '5552229000', NULL,
  'https://www.inbursa.com/pagos',
  'https://apps.apple.com/mx/app/inbursa-movil/id977399048',
  'https://play.google.com/store/apps/details?id=com.inbursa.inbursamovil',
  'https://www.inbursa.com/condiciones-generales',
  'Servicio de siniestros disponible. Proporciona tu informacion de poliza al contactar.',
  true, true, true, 14),
('Banorte Seguros', 'https://logo.clearbit.com/banorte.com',
  '8008008765', '8008008765', NULL,
  'https://www.banorte.com/seguros/pagos',
  'https://apps.apple.com/mx/app/banorte-movil/id1030826950',
  'https://play.google.com/store/apps/details?id=com.banorte.movil',
  'https://www.banorte.com/seguros/condiciones-generales',
  'Reporta tu siniestro de vida, autos o bienes. Ten tu numero de poliza disponible.',
  true, true, true, 15),
('Proteccion Mutua', 'https://logo.clearbit.com/proteccionmutua.com.mx',
  '5552007777', '5552007777', NULL,
  NULL, NULL, NULL, NULL,
  'Contacta nuestra linea de atencion para reportar cualquier siniestro.',
  true, true, true, 16),
('Mutuus Salud Inteligente', 'https://logo.clearbit.com/mutuus.mx',
  '5551302020', '5551302020', NULL,
  'https://www.mutuus.mx/pagos',
  NULL, NULL,
  'https://www.mutuus.mx/condiciones-generales',
  'Especialistas en gastos medicos mayores. Contacta para autorizaciones y reembolsos.',
  true, true, true, 17),
('Dorama Seguros', 'https://logo.clearbit.com/dorama.com.mx',
  '5558503000', '5558503000', NULL,
  NULL, NULL, NULL, NULL,
  'Reporta tu siniestro proporcionando tu numero de poliza y datos del evento.',
  true, true, true, 18),
('BX+ Fianzas', 'https://logo.clearbit.com/bx.com.mx',
  '5555229190', NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  true, false, true, 19),
('Liberty Fianzas', 'https://logo.clearbit.com/liberty.com.mx',
  '8001232300', NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  true, false, true, 20),
('Dentegra Seguros Dentales', 'https://logo.clearbit.com/dentegra.com.mx',
  '5557246600', '5557246600', NULL,
  'https://www.dentegra.com.mx/pagos',
  NULL, NULL,
  'https://www.dentegra.com.mx/condiciones-generales',
  'Para urgencias dentales o autorizaciones de tratamiento, contacta nuestra linea.',
  true, true, true, 21),
('Afirme Seguros', 'https://logo.clearbit.com/afirme.com',
  '8008003700', '8008003700', NULL,
  'https://www.afirme.com/seguros/pagos',
  NULL, NULL,
  'https://www.afirme.com/seguros/condiciones-generales',
  'Reporta tu siniestro con tu numero de poliza a la mano.',
  true, true, true, 22),
('Seguros El Potosi', 'https://logo.clearbit.com/elpotosi.com.mx',
  '4448343600', '4448343600', NULL,
  NULL, NULL, NULL, NULL,
  'Reporta tu siniestro en nuestra linea directa.',
  true, true, true, 23),
('HIR Seguros', 'https://logo.clearbit.com/hir.com.mx',
  '5591775000', '5591775000', NULL,
  NULL, NULL, NULL, NULL,
  'Contacta nuestra linea para reportar siniestros de hogar o vida.',
  true, true, true, 24),
('Thona Seguros', 'https://logo.clearbit.com/thona.com.mx',
  '5552630000', '5552630000', NULL,
  NULL, NULL, NULL, NULL,
  'Reporta tu siniestro de autos o transporte. Cobertura nacional.',
  true, true, true, 25),
('Aserta Grupo Financiero', 'https://logo.clearbit.com/aserta.com.mx',
  '5591282200', NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  true, false, true, 26),
('Insignia Life', 'https://logo.clearbit.com/insignialife.com',
  '5552617700', '5552617700', NULL,
  NULL, NULL, NULL, NULL,
  'Para siniestros de vida e invalidez, contacta nuestra linea especializada.',
  true, true, true, 27);
